Fixing an issue with booleans on CockroachDB v22.2
cockroachdb/university-getting-started-with-sql-app-exercises pull request #9
Opened 2023-01-16 20:50 UTC by thatnerd

- Problem caused because shell now uses `t` and `f` rather than `true` and `false` (change was made to align with postgreSQL shell)
- Added a function to convert `t` to `true` and `f` to `false` and anything else to itself.
- Modified an index test that didn't store the non_unique result and check it, but just checked an entire line.

2023-01-16 21:00 UTC, alexyarosh commented
@thatnerd Can you update the CI to use 22.2?

2023-01-16 21:01 UTC, alexyarosh requested changes
@thatnerd can you update the CI to use 22.2?

2023-01-17 14:09 UTC, thatnerd commented
> @thatnerd can you update the CI to use 22.2?

Will do!

2023-01-17 15:44 UTC, alexyarosh approved these changes

2023-01-17 16:10 UTC, merged